### PR TITLE
Fixed bsf file and some typos

### PR DESCRIPTION
**Pull request by memristor2**
I have fixed the bsf file for EagleStream so it can now be opened and edited with the Binary Configuration Tool and then patched to the FSP binary. Also the lowercase "s" in EagleStream was set to uppercase "S"

### CODE REVIEW

**Comment by memristor2** [comment]
Resolves: https://github.com/intel/FSP/issues/99

**Comment by nate-desimone** [comment]
Hi @memristor2 - Thank you for your contribution!

Due to legal issues, we are unable to accept PRs from people who were not Intel employees at the time the PR was submitted. We appreciate your enthusiasm and thank you for your support.

**Comment by memristor2** [comment]
Hi @nate-desimone,
I understand this. I am waiting for the EagleStream patch in edk2-platforms. But since that is going to take a while I thought maybe issuing a PR would be a mere reminder for the fact that the EagleStream's FSP is incomplete. My saying is simply based on FSP External Architecture  which states the FSP distrubition package must contain some things that I am not going to mention since Im sure that you are aware of it better than me. I was wondering if you could atleast relase the integration guide for EagleStream.
Thanks

**Comment by nate-desimone** [comment]
Hi @memristor2 - I can confirm that several people at Intel including myself and working to resolve the concerns that you mention, and the concerns you bring up in this PR.

**Pull request closed without merging**
